### PR TITLE
Added basic files and notebooks, trained models

### PR DESCRIPTION
**Pull request by yorkiva**
I have added the training files, some trained models, and the notebooks. The notebooks will need some rework to comply with the new project structure.

### CODE REVIEW

**Comment by jmduarte** [comment]
Hi @yorkiva,

Thanks for the PR!

Can you clean up some of the scripts that aren't actually used in the studies in the paper, for instance, https://github.com/yorkiva/hbb_interaction_network/blob/main/src/models/IN_dataGenerator_QCDreweight.py, etc.

Also can you merge your training script with the existing training script?: https://github.com/FAIR4HEP/hbb_interaction_network/blob/main/src/models/train_model.py

I also don't believe these files are necessary for any studies:
https://github.com/yorkiva/hbb_interaction_network/blob/main/src/models/ddb.py
https://github.com/yorkiva/hbb_interaction_network/blob/main/src/models/DDB_eval_keras.py
https://github.com/yorkiva/hbb_interaction_network/blob/main/src/models/DDB_eval_keras.py

Also this file can be renamed https://github.com/yorkiva/hbb_interaction_network/blob/main/src/models/IN_eval.py to `predict_model.py`, etc.

Thanks!

**Review by jmduarte — CHANGES_REQUESTED** [review]
Hi @yorkiva,

Thanks for the PR!

- [x] Can you clean up some of the scripts that aren't actually used in the studies in the paper, for instance, https://github.com/yorkiva/hbb_interaction_network/blob/main/src/models/IN_dataGenerator_QCDreweight.py, etc.
- [x] Can you also merge your training script with the existing training script?: https://github.com/FAIR4HEP/hbb_interaction_network/blob/main/src/models/train_model.py
- [x] I also don't believe these files are necessary for any studies:
https://github.com/yorkiva/hbb_interaction_network/blob/main/src/models/ddb.py
https://github.com/yorkiva/hbb_interaction_network/blob/main/src/models/DDB_eval_keras.py
https://github.com/yorkiva/hbb_interaction_network/blob/main/src/models/DDB_eval_keras.py
- [x] Also this file can be renamed https://github.com/yorkiva/hbb_interaction_network/blob/main/src/models/IN_eval.py to predict_model.py, etc.
- [x] Also, if you can install `pre-commit` (https://pre-commit.com/) and run those checks, that would be great (`black`, `flake8`, `isort`, etc.)

Thanks!

**Comment by yorkiva** [comment]
I have removed the unnecessary files and renamed the training and evaluation scripts. The training script has some modifications of my own to (1) allow training models where some features are dropped and (2) create a model metadata to allow access to model's structure and hyperparameters (check examples in `models/model_dicts`). Also, the only model I have used is the "default" architecture, which is the `GraphNet` class in `gnn.py`

**Review by jmduarte — CHANGES_REQUESTED** [review]
hi @yorkiva thanks! getting closer.

- [x] still need to remove `ddb.py`
- [x] resolve the conflicts with the existing `train_model.py`
- [x] `gnn.py` was already renamed `models.py` and the class was renamed so check if it's consistent/usable and use that
- [x] `models/data.py` was moved into `data/h5data.py` so remove your version and use the existing version (but check to make sure its consistent/usable first
- [x] `pre-commit run --all` returns lots of (minor) issues to fix, but first, i would definitely remove unnecessary files

**Comment by yorkiva** [comment]
I have removed most of the unwanted scripts. Things that remain:

- [ ] updating the `predict_model.py` script to incorporate the current repo structure
- [x] updating my notebooks to be compatible with the current repo structure

**Review by jmduarte — APPROVED** [review]
LGTM!

**Pull request merged**
